Search.appendIndex(
    [
                {
            "fqsen": "\\FPDF",
            "name": "FPDF",
            "summary": "",
            "url": "classes/FPDF.html"
        },                {
            "fqsen": "\\FPDF\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/FPDF.html#method___construct"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetMargins\u0028\u0029",
            "name": "SetMargins",
            "summary": "",
            "url": "classes/FPDF.html#method_SetMargins"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetLeftMargin\u0028\u0029",
            "name": "SetLeftMargin",
            "summary": "",
            "url": "classes/FPDF.html#method_SetLeftMargin"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetTopMargin\u0028\u0029",
            "name": "SetTopMargin",
            "summary": "",
            "url": "classes/FPDF.html#method_SetTopMargin"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetRightMargin\u0028\u0029",
            "name": "SetRightMargin",
            "summary": "",
            "url": "classes/FPDF.html#method_SetRightMargin"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetAutoPageBreak\u0028\u0029",
            "name": "SetAutoPageBreak",
            "summary": "",
            "url": "classes/FPDF.html#method_SetAutoPageBreak"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetDisplayMode\u0028\u0029",
            "name": "SetDisplayMode",
            "summary": "",
            "url": "classes/FPDF.html#method_SetDisplayMode"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetCompression\u0028\u0029",
            "name": "SetCompression",
            "summary": "",
            "url": "classes/FPDF.html#method_SetCompression"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetTitle\u0028\u0029",
            "name": "SetTitle",
            "summary": "",
            "url": "classes/FPDF.html#method_SetTitle"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetAuthor\u0028\u0029",
            "name": "SetAuthor",
            "summary": "",
            "url": "classes/FPDF.html#method_SetAuthor"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetSubject\u0028\u0029",
            "name": "SetSubject",
            "summary": "",
            "url": "classes/FPDF.html#method_SetSubject"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetKeywords\u0028\u0029",
            "name": "SetKeywords",
            "summary": "",
            "url": "classes/FPDF.html#method_SetKeywords"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetCreator\u0028\u0029",
            "name": "SetCreator",
            "summary": "",
            "url": "classes/FPDF.html#method_SetCreator"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024AliasNbPages",
            "name": "AliasNbPages",
            "summary": "",
            "url": "classes/FPDF.html#property_AliasNbPages"
        },                {
            "fqsen": "\\FPDF\u003A\u003AError\u0028\u0029",
            "name": "Error",
            "summary": "",
            "url": "classes/FPDF.html#method_Error"
        },                {
            "fqsen": "\\FPDF\u003A\u003AClose\u0028\u0029",
            "name": "Close",
            "summary": "",
            "url": "classes/FPDF.html#method_Close"
        },                {
            "fqsen": "\\FPDF\u003A\u003AAddPage\u0028\u0029",
            "name": "AddPage",
            "summary": "",
            "url": "classes/FPDF.html#method_AddPage"
        },                {
            "fqsen": "\\FPDF\u003A\u003AHeader\u0028\u0029",
            "name": "Header",
            "summary": "",
            "url": "classes/FPDF.html#method_Header"
        },                {
            "fqsen": "\\FPDF\u003A\u003AFooter\u0028\u0029",
            "name": "Footer",
            "summary": "",
            "url": "classes/FPDF.html#method_Footer"
        },                {
            "fqsen": "\\FPDF\u003A\u003APageNo\u0028\u0029",
            "name": "PageNo",
            "summary": "",
            "url": "classes/FPDF.html#method_PageNo"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetDrawColor\u0028\u0029",
            "name": "SetDrawColor",
            "summary": "",
            "url": "classes/FPDF.html#method_SetDrawColor"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetFillColor\u0028\u0029",
            "name": "SetFillColor",
            "summary": "",
            "url": "classes/FPDF.html#method_SetFillColor"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetTextColor\u0028\u0029",
            "name": "SetTextColor",
            "summary": "",
            "url": "classes/FPDF.html#method_SetTextColor"
        },                {
            "fqsen": "\\FPDF\u003A\u003AGetStringWidth\u0028\u0029",
            "name": "GetStringWidth",
            "summary": "",
            "url": "classes/FPDF.html#method_GetStringWidth"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetLineWidth\u0028\u0029",
            "name": "SetLineWidth",
            "summary": "",
            "url": "classes/FPDF.html#method_SetLineWidth"
        },                {
            "fqsen": "\\FPDF\u003A\u003ALine\u0028\u0029",
            "name": "Line",
            "summary": "",
            "url": "classes/FPDF.html#method_Line"
        },                {
            "fqsen": "\\FPDF\u003A\u003ARect\u0028\u0029",
            "name": "Rect",
            "summary": "",
            "url": "classes/FPDF.html#method_Rect"
        },                {
            "fqsen": "\\FPDF\u003A\u003AAddFont\u0028\u0029",
            "name": "AddFont",
            "summary": "",
            "url": "classes/FPDF.html#method_AddFont"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetFont\u0028\u0029",
            "name": "SetFont",
            "summary": "",
            "url": "classes/FPDF.html#method_SetFont"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetFontSize\u0028\u0029",
            "name": "SetFontSize",
            "summary": "",
            "url": "classes/FPDF.html#method_SetFontSize"
        },                {
            "fqsen": "\\FPDF\u003A\u003AAddLink\u0028\u0029",
            "name": "AddLink",
            "summary": "",
            "url": "classes/FPDF.html#method_AddLink"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetLink\u0028\u0029",
            "name": "SetLink",
            "summary": "",
            "url": "classes/FPDF.html#method_SetLink"
        },                {
            "fqsen": "\\FPDF\u003A\u003ALink\u0028\u0029",
            "name": "Link",
            "summary": "",
            "url": "classes/FPDF.html#method_Link"
        },                {
            "fqsen": "\\FPDF\u003A\u003AText\u0028\u0029",
            "name": "Text",
            "summary": "",
            "url": "classes/FPDF.html#method_Text"
        },                {
            "fqsen": "\\FPDF\u003A\u003AAcceptPageBreak\u0028\u0029",
            "name": "AcceptPageBreak",
            "summary": "",
            "url": "classes/FPDF.html#method_AcceptPageBreak"
        },                {
            "fqsen": "\\FPDF\u003A\u003ACell\u0028\u0029",
            "name": "Cell",
            "summary": "",
            "url": "classes/FPDF.html#method_Cell"
        },                {
            "fqsen": "\\FPDF\u003A\u003AMultiCell\u0028\u0029",
            "name": "MultiCell",
            "summary": "",
            "url": "classes/FPDF.html#method_MultiCell"
        },                {
            "fqsen": "\\FPDF\u003A\u003AWrite\u0028\u0029",
            "name": "Write",
            "summary": "",
            "url": "classes/FPDF.html#method_Write"
        },                {
            "fqsen": "\\FPDF\u003A\u003ALn\u0028\u0029",
            "name": "Ln",
            "summary": "",
            "url": "classes/FPDF.html#method_Ln"
        },                {
            "fqsen": "\\FPDF\u003A\u003AImage\u0028\u0029",
            "name": "Image",
            "summary": "",
            "url": "classes/FPDF.html#method_Image"
        },                {
            "fqsen": "\\FPDF\u003A\u003AGetPageWidth\u0028\u0029",
            "name": "GetPageWidth",
            "summary": "",
            "url": "classes/FPDF.html#method_GetPageWidth"
        },                {
            "fqsen": "\\FPDF\u003A\u003AGetPageHeight\u0028\u0029",
            "name": "GetPageHeight",
            "summary": "",
            "url": "classes/FPDF.html#method_GetPageHeight"
        },                {
            "fqsen": "\\FPDF\u003A\u003AGetX\u0028\u0029",
            "name": "GetX",
            "summary": "",
            "url": "classes/FPDF.html#method_GetX"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetX\u0028\u0029",
            "name": "SetX",
            "summary": "",
            "url": "classes/FPDF.html#method_SetX"
        },                {
            "fqsen": "\\FPDF\u003A\u003AGetY\u0028\u0029",
            "name": "GetY",
            "summary": "",
            "url": "classes/FPDF.html#method_GetY"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetY\u0028\u0029",
            "name": "SetY",
            "summary": "",
            "url": "classes/FPDF.html#method_SetY"
        },                {
            "fqsen": "\\FPDF\u003A\u003ASetXY\u0028\u0029",
            "name": "SetXY",
            "summary": "",
            "url": "classes/FPDF.html#method_SetXY"
        },                {
            "fqsen": "\\FPDF\u003A\u003AOutput\u0028\u0029",
            "name": "Output",
            "summary": "",
            "url": "classes/FPDF.html#method_Output"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_checkoutput\u0028\u0029",
            "name": "_checkoutput",
            "summary": "",
            "url": "classes/FPDF.html#method__checkoutput"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_getpagesize\u0028\u0029",
            "name": "_getpagesize",
            "summary": "",
            "url": "classes/FPDF.html#method__getpagesize"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_beginpage\u0028\u0029",
            "name": "_beginpage",
            "summary": "",
            "url": "classes/FPDF.html#method__beginpage"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_endpage\u0028\u0029",
            "name": "_endpage",
            "summary": "",
            "url": "classes/FPDF.html#method__endpage"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_loadfont\u0028\u0029",
            "name": "_loadfont",
            "summary": "",
            "url": "classes/FPDF.html#method__loadfont"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_isascii\u0028\u0029",
            "name": "_isascii",
            "summary": "",
            "url": "classes/FPDF.html#method__isascii"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_httpencode\u0028\u0029",
            "name": "_httpencode",
            "summary": "",
            "url": "classes/FPDF.html#method__httpencode"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_UTF8encode\u0028\u0029",
            "name": "_UTF8encode",
            "summary": "",
            "url": "classes/FPDF.html#method__UTF8encode"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_UTF8toUTF16\u0028\u0029",
            "name": "_UTF8toUTF16",
            "summary": "",
            "url": "classes/FPDF.html#method__UTF8toUTF16"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_escape\u0028\u0029",
            "name": "_escape",
            "summary": "",
            "url": "classes/FPDF.html#method__escape"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_textstring\u0028\u0029",
            "name": "_textstring",
            "summary": "",
            "url": "classes/FPDF.html#method__textstring"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_dounderline\u0028\u0029",
            "name": "_dounderline",
            "summary": "",
            "url": "classes/FPDF.html#method__dounderline"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_parsejpg\u0028\u0029",
            "name": "_parsejpg",
            "summary": "",
            "url": "classes/FPDF.html#method__parsejpg"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_parsepng\u0028\u0029",
            "name": "_parsepng",
            "summary": "",
            "url": "classes/FPDF.html#method__parsepng"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_parsepngstream\u0028\u0029",
            "name": "_parsepngstream",
            "summary": "",
            "url": "classes/FPDF.html#method__parsepngstream"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_readstream\u0028\u0029",
            "name": "_readstream",
            "summary": "",
            "url": "classes/FPDF.html#method__readstream"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_readint\u0028\u0029",
            "name": "_readint",
            "summary": "",
            "url": "classes/FPDF.html#method__readint"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_parsegif\u0028\u0029",
            "name": "_parsegif",
            "summary": "",
            "url": "classes/FPDF.html#method__parsegif"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_out\u0028\u0029",
            "name": "_out",
            "summary": "",
            "url": "classes/FPDF.html#method__out"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_put\u0028\u0029",
            "name": "_put",
            "summary": "",
            "url": "classes/FPDF.html#method__put"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_getoffset\u0028\u0029",
            "name": "_getoffset",
            "summary": "",
            "url": "classes/FPDF.html#method__getoffset"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_newobj\u0028\u0029",
            "name": "_newobj",
            "summary": "",
            "url": "classes/FPDF.html#method__newobj"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_putstream\u0028\u0029",
            "name": "_putstream",
            "summary": "",
            "url": "classes/FPDF.html#method__putstream"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_putstreamobject\u0028\u0029",
            "name": "_putstreamobject",
            "summary": "",
            "url": "classes/FPDF.html#method__putstreamobject"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_putlinks\u0028\u0029",
            "name": "_putlinks",
            "summary": "",
            "url": "classes/FPDF.html#method__putlinks"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_putpage\u0028\u0029",
            "name": "_putpage",
            "summary": "",
            "url": "classes/FPDF.html#method__putpage"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_putpages\u0028\u0029",
            "name": "_putpages",
            "summary": "",
            "url": "classes/FPDF.html#method__putpages"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_putfonts\u0028\u0029",
            "name": "_putfonts",
            "summary": "",
            "url": "classes/FPDF.html#method__putfonts"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_tounicodecmap\u0028\u0029",
            "name": "_tounicodecmap",
            "summary": "",
            "url": "classes/FPDF.html#method__tounicodecmap"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_putimages\u0028\u0029",
            "name": "_putimages",
            "summary": "",
            "url": "classes/FPDF.html#method__putimages"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_putimage\u0028\u0029",
            "name": "_putimage",
            "summary": "",
            "url": "classes/FPDF.html#method__putimage"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_putxobjectdict\u0028\u0029",
            "name": "_putxobjectdict",
            "summary": "",
            "url": "classes/FPDF.html#method__putxobjectdict"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_putresourcedict\u0028\u0029",
            "name": "_putresourcedict",
            "summary": "",
            "url": "classes/FPDF.html#method__putresourcedict"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_putresources\u0028\u0029",
            "name": "_putresources",
            "summary": "",
            "url": "classes/FPDF.html#method__putresources"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_putinfo\u0028\u0029",
            "name": "_putinfo",
            "summary": "",
            "url": "classes/FPDF.html#method__putinfo"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_putcatalog\u0028\u0029",
            "name": "_putcatalog",
            "summary": "",
            "url": "classes/FPDF.html#method__putcatalog"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_putheader\u0028\u0029",
            "name": "_putheader",
            "summary": "",
            "url": "classes/FPDF.html#method__putheader"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_puttrailer\u0028\u0029",
            "name": "_puttrailer",
            "summary": "",
            "url": "classes/FPDF.html#method__puttrailer"
        },                {
            "fqsen": "\\FPDF\u003A\u003A_enddoc\u0028\u0029",
            "name": "_enddoc",
            "summary": "",
            "url": "classes/FPDF.html#method__enddoc"
        },                {
            "fqsen": "\\FPDF\u003A\u003AVERSION",
            "name": "VERSION",
            "summary": "",
            "url": "classes/FPDF.html#constant_VERSION"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024page",
            "name": "page",
            "summary": "",
            "url": "classes/FPDF.html#property_page"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024n",
            "name": "n",
            "summary": "",
            "url": "classes/FPDF.html#property_n"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024offsets",
            "name": "offsets",
            "summary": "",
            "url": "classes/FPDF.html#property_offsets"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024buffer",
            "name": "buffer",
            "summary": "",
            "url": "classes/FPDF.html#property_buffer"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024pages",
            "name": "pages",
            "summary": "",
            "url": "classes/FPDF.html#property_pages"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024state",
            "name": "state",
            "summary": "",
            "url": "classes/FPDF.html#property_state"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024compress",
            "name": "compress",
            "summary": "",
            "url": "classes/FPDF.html#property_compress"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024iconv",
            "name": "iconv",
            "summary": "",
            "url": "classes/FPDF.html#property_iconv"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024k",
            "name": "k",
            "summary": "",
            "url": "classes/FPDF.html#property_k"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024DefOrientation",
            "name": "DefOrientation",
            "summary": "",
            "url": "classes/FPDF.html#property_DefOrientation"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024CurOrientation",
            "name": "CurOrientation",
            "summary": "",
            "url": "classes/FPDF.html#property_CurOrientation"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024StdPageSizes",
            "name": "StdPageSizes",
            "summary": "",
            "url": "classes/FPDF.html#property_StdPageSizes"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024DefPageSize",
            "name": "DefPageSize",
            "summary": "",
            "url": "classes/FPDF.html#property_DefPageSize"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024CurPageSize",
            "name": "CurPageSize",
            "summary": "",
            "url": "classes/FPDF.html#property_CurPageSize"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024CurRotation",
            "name": "CurRotation",
            "summary": "",
            "url": "classes/FPDF.html#property_CurRotation"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024PageInfo",
            "name": "PageInfo",
            "summary": "",
            "url": "classes/FPDF.html#property_PageInfo"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024wPt",
            "name": "wPt",
            "summary": "",
            "url": "classes/FPDF.html#property_wPt"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024hPt",
            "name": "hPt",
            "summary": "",
            "url": "classes/FPDF.html#property_hPt"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024w",
            "name": "w",
            "summary": "",
            "url": "classes/FPDF.html#property_w"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024h",
            "name": "h",
            "summary": "",
            "url": "classes/FPDF.html#property_h"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024lMargin",
            "name": "lMargin",
            "summary": "",
            "url": "classes/FPDF.html#property_lMargin"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024tMargin",
            "name": "tMargin",
            "summary": "",
            "url": "classes/FPDF.html#property_tMargin"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024rMargin",
            "name": "rMargin",
            "summary": "",
            "url": "classes/FPDF.html#property_rMargin"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024bMargin",
            "name": "bMargin",
            "summary": "",
            "url": "classes/FPDF.html#property_bMargin"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024cMargin",
            "name": "cMargin",
            "summary": "",
            "url": "classes/FPDF.html#property_cMargin"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024x",
            "name": "x",
            "summary": "",
            "url": "classes/FPDF.html#property_x"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024y",
            "name": "y",
            "summary": "",
            "url": "classes/FPDF.html#property_y"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024lasth",
            "name": "lasth",
            "summary": "",
            "url": "classes/FPDF.html#property_lasth"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024LineWidth",
            "name": "LineWidth",
            "summary": "",
            "url": "classes/FPDF.html#property_LineWidth"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024fontpath",
            "name": "fontpath",
            "summary": "",
            "url": "classes/FPDF.html#property_fontpath"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024CoreFonts",
            "name": "CoreFonts",
            "summary": "",
            "url": "classes/FPDF.html#property_CoreFonts"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024fonts",
            "name": "fonts",
            "summary": "",
            "url": "classes/FPDF.html#property_fonts"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024FontFiles",
            "name": "FontFiles",
            "summary": "",
            "url": "classes/FPDF.html#property_FontFiles"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024encodings",
            "name": "encodings",
            "summary": "",
            "url": "classes/FPDF.html#property_encodings"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024cmaps",
            "name": "cmaps",
            "summary": "",
            "url": "classes/FPDF.html#property_cmaps"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024FontFamily",
            "name": "FontFamily",
            "summary": "",
            "url": "classes/FPDF.html#property_FontFamily"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024FontStyle",
            "name": "FontStyle",
            "summary": "",
            "url": "classes/FPDF.html#property_FontStyle"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024underline",
            "name": "underline",
            "summary": "",
            "url": "classes/FPDF.html#property_underline"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024CurrentFont",
            "name": "CurrentFont",
            "summary": "",
            "url": "classes/FPDF.html#property_CurrentFont"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024FontSizePt",
            "name": "FontSizePt",
            "summary": "",
            "url": "classes/FPDF.html#property_FontSizePt"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024FontSize",
            "name": "FontSize",
            "summary": "",
            "url": "classes/FPDF.html#property_FontSize"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024DrawColor",
            "name": "DrawColor",
            "summary": "",
            "url": "classes/FPDF.html#property_DrawColor"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024FillColor",
            "name": "FillColor",
            "summary": "",
            "url": "classes/FPDF.html#property_FillColor"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024TextColor",
            "name": "TextColor",
            "summary": "",
            "url": "classes/FPDF.html#property_TextColor"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024ColorFlag",
            "name": "ColorFlag",
            "summary": "",
            "url": "classes/FPDF.html#property_ColorFlag"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024WithAlpha",
            "name": "WithAlpha",
            "summary": "",
            "url": "classes/FPDF.html#property_WithAlpha"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024ws",
            "name": "ws",
            "summary": "",
            "url": "classes/FPDF.html#property_ws"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024images",
            "name": "images",
            "summary": "",
            "url": "classes/FPDF.html#property_images"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024PageLinks",
            "name": "PageLinks",
            "summary": "",
            "url": "classes/FPDF.html#property_PageLinks"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024links",
            "name": "links",
            "summary": "",
            "url": "classes/FPDF.html#property_links"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024AutoPageBreak",
            "name": "AutoPageBreak",
            "summary": "",
            "url": "classes/FPDF.html#property_AutoPageBreak"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024PageBreakTrigger",
            "name": "PageBreakTrigger",
            "summary": "",
            "url": "classes/FPDF.html#property_PageBreakTrigger"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024InHeader",
            "name": "InHeader",
            "summary": "",
            "url": "classes/FPDF.html#property_InHeader"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024InFooter",
            "name": "InFooter",
            "summary": "",
            "url": "classes/FPDF.html#property_InFooter"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024ZoomMode",
            "name": "ZoomMode",
            "summary": "",
            "url": "classes/FPDF.html#property_ZoomMode"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024LayoutMode",
            "name": "LayoutMode",
            "summary": "",
            "url": "classes/FPDF.html#property_LayoutMode"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024metadata",
            "name": "metadata",
            "summary": "",
            "url": "classes/FPDF.html#property_metadata"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024CreationDate",
            "name": "CreationDate",
            "summary": "",
            "url": "classes/FPDF.html#property_CreationDate"
        },                {
            "fqsen": "\\FPDF\u003A\u003A\u0024PDFVersion",
            "name": "PDFVersion",
            "summary": "",
            "url": "classes/FPDF.html#property_PDFVersion"
        },                {
            "fqsen": "\\Message\u0028\u0029",
            "name": "Message",
            "summary": "",
            "url": "namespaces/default.html#function_Message"
        },                {
            "fqsen": "\\Notice\u0028\u0029",
            "name": "Notice",
            "summary": "",
            "url": "namespaces/default.html#function_Notice"
        },                {
            "fqsen": "\\Warning\u0028\u0029",
            "name": "Warning",
            "summary": "",
            "url": "namespaces/default.html#function_Warning"
        },                {
            "fqsen": "\\Error\u0028\u0029",
            "name": "Error",
            "summary": "",
            "url": "namespaces/default.html#function_Error"
        },                {
            "fqsen": "\\LoadMap\u0028\u0029",
            "name": "LoadMap",
            "summary": "",
            "url": "namespaces/default.html#function_LoadMap"
        },                {
            "fqsen": "\\GetInfoFromTrueType\u0028\u0029",
            "name": "GetInfoFromTrueType",
            "summary": "",
            "url": "namespaces/default.html#function_GetInfoFromTrueType"
        },                {
            "fqsen": "\\GetInfoFromType1\u0028\u0029",
            "name": "GetInfoFromType1",
            "summary": "",
            "url": "namespaces/default.html#function_GetInfoFromType1"
        },                {
            "fqsen": "\\MakeFontDescriptor\u0028\u0029",
            "name": "MakeFontDescriptor",
            "summary": "",
            "url": "namespaces/default.html#function_MakeFontDescriptor"
        },                {
            "fqsen": "\\MakeWidthArray\u0028\u0029",
            "name": "MakeWidthArray",
            "summary": "",
            "url": "namespaces/default.html#function_MakeWidthArray"
        },                {
            "fqsen": "\\MakeFontEncoding\u0028\u0029",
            "name": "MakeFontEncoding",
            "summary": "",
            "url": "namespaces/default.html#function_MakeFontEncoding"
        },                {
            "fqsen": "\\MakeUnicodeArray\u0028\u0029",
            "name": "MakeUnicodeArray",
            "summary": "",
            "url": "namespaces/default.html#function_MakeUnicodeArray"
        },                {
            "fqsen": "\\SaveToFile\u0028\u0029",
            "name": "SaveToFile",
            "summary": "",
            "url": "namespaces/default.html#function_SaveToFile"
        },                {
            "fqsen": "\\MakeDefinitionFile\u0028\u0029",
            "name": "MakeDefinitionFile",
            "summary": "",
            "url": "namespaces/default.html#function_MakeDefinitionFile"
        },                {
            "fqsen": "\\MakeFont\u0028\u0029",
            "name": "MakeFont",
            "summary": "",
            "url": "namespaces/default.html#function_MakeFont"
        },                {
            "fqsen": "\\TTFParser",
            "name": "TTFParser",
            "summary": "",
            "url": "classes/TTFParser.html"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/TTFParser.html#method___construct"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "",
            "url": "classes/TTFParser.html#method___destruct"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AParse\u0028\u0029",
            "name": "Parse",
            "summary": "",
            "url": "classes/TTFParser.html#method_Parse"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AParseOffsetTable\u0028\u0029",
            "name": "ParseOffsetTable",
            "summary": "",
            "url": "classes/TTFParser.html#method_ParseOffsetTable"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AParseHead\u0028\u0029",
            "name": "ParseHead",
            "summary": "",
            "url": "classes/TTFParser.html#method_ParseHead"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AParseHhea\u0028\u0029",
            "name": "ParseHhea",
            "summary": "",
            "url": "classes/TTFParser.html#method_ParseHhea"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AParseMaxp\u0028\u0029",
            "name": "ParseMaxp",
            "summary": "",
            "url": "classes/TTFParser.html#method_ParseMaxp"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AParseHmtx\u0028\u0029",
            "name": "ParseHmtx",
            "summary": "",
            "url": "classes/TTFParser.html#method_ParseHmtx"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AParseLoca\u0028\u0029",
            "name": "ParseLoca",
            "summary": "",
            "url": "classes/TTFParser.html#method_ParseLoca"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AParseGlyf\u0028\u0029",
            "name": "ParseGlyf",
            "summary": "",
            "url": "classes/TTFParser.html#method_ParseGlyf"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AParseCmap\u0028\u0029",
            "name": "ParseCmap",
            "summary": "",
            "url": "classes/TTFParser.html#method_ParseCmap"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AParseName\u0028\u0029",
            "name": "ParseName",
            "summary": "",
            "url": "classes/TTFParser.html#method_ParseName"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AParseOS2\u0028\u0029",
            "name": "ParseOS2",
            "summary": "",
            "url": "classes/TTFParser.html#method_ParseOS2"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AParsePost\u0028\u0029",
            "name": "ParsePost",
            "summary": "",
            "url": "classes/TTFParser.html#method_ParsePost"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ASubset\u0028\u0029",
            "name": "Subset",
            "summary": "",
            "url": "classes/TTFParser.html#method_Subset"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AAddGlyph\u0028\u0029",
            "name": "AddGlyph",
            "summary": "",
            "url": "classes/TTFParser.html#method_AddGlyph"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ABuild\u0028\u0029",
            "name": "Build",
            "summary": "",
            "url": "classes/TTFParser.html#method_Build"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ABuildCmap\u0028\u0029",
            "name": "BuildCmap",
            "summary": "",
            "url": "classes/TTFParser.html#method_BuildCmap"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ABuildHhea\u0028\u0029",
            "name": "BuildHhea",
            "summary": "",
            "url": "classes/TTFParser.html#method_BuildHhea"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ABuildHmtx\u0028\u0029",
            "name": "BuildHmtx",
            "summary": "",
            "url": "classes/TTFParser.html#method_BuildHmtx"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ABuildLoca\u0028\u0029",
            "name": "BuildLoca",
            "summary": "",
            "url": "classes/TTFParser.html#method_BuildLoca"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ABuildGlyf\u0028\u0029",
            "name": "BuildGlyf",
            "summary": "",
            "url": "classes/TTFParser.html#method_BuildGlyf"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ABuildMaxp\u0028\u0029",
            "name": "BuildMaxp",
            "summary": "",
            "url": "classes/TTFParser.html#method_BuildMaxp"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ABuildPost\u0028\u0029",
            "name": "BuildPost",
            "summary": "",
            "url": "classes/TTFParser.html#method_BuildPost"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ABuildFont\u0028\u0029",
            "name": "BuildFont",
            "summary": "",
            "url": "classes/TTFParser.html#method_BuildFont"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ALoadTable\u0028\u0029",
            "name": "LoadTable",
            "summary": "",
            "url": "classes/TTFParser.html#method_LoadTable"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ASetTable\u0028\u0029",
            "name": "SetTable",
            "summary": "",
            "url": "classes/TTFParser.html#method_SetTable"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ASeek\u0028\u0029",
            "name": "Seek",
            "summary": "",
            "url": "classes/TTFParser.html#method_Seek"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ASkip\u0028\u0029",
            "name": "Skip",
            "summary": "",
            "url": "classes/TTFParser.html#method_Skip"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ARead\u0028\u0029",
            "name": "Read",
            "summary": "",
            "url": "classes/TTFParser.html#method_Read"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AReadUShort\u0028\u0029",
            "name": "ReadUShort",
            "summary": "",
            "url": "classes/TTFParser.html#method_ReadUShort"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AReadShort\u0028\u0029",
            "name": "ReadShort",
            "summary": "",
            "url": "classes/TTFParser.html#method_ReadShort"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AReadULong\u0028\u0029",
            "name": "ReadULong",
            "summary": "",
            "url": "classes/TTFParser.html#method_ReadULong"
        },                {
            "fqsen": "\\TTFParser\u003A\u003ACheckSum\u0028\u0029",
            "name": "CheckSum",
            "summary": "",
            "url": "classes/TTFParser.html#method_CheckSum"
        },                {
            "fqsen": "\\TTFParser\u003A\u003AError\u0028\u0029",
            "name": "Error",
            "summary": "",
            "url": "classes/TTFParser.html#method_Error"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024f",
            "name": "f",
            "summary": "",
            "url": "classes/TTFParser.html#property_f"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024tables",
            "name": "tables",
            "summary": "",
            "url": "classes/TTFParser.html#property_tables"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024numberOfHMetrics",
            "name": "numberOfHMetrics",
            "summary": "",
            "url": "classes/TTFParser.html#property_numberOfHMetrics"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024numGlyphs",
            "name": "numGlyphs",
            "summary": "",
            "url": "classes/TTFParser.html#property_numGlyphs"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024glyphNames",
            "name": "glyphNames",
            "summary": "",
            "url": "classes/TTFParser.html#property_glyphNames"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024indexToLocFormat",
            "name": "indexToLocFormat",
            "summary": "",
            "url": "classes/TTFParser.html#property_indexToLocFormat"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024subsettedChars",
            "name": "subsettedChars",
            "summary": "",
            "url": "classes/TTFParser.html#property_subsettedChars"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024subsettedGlyphs",
            "name": "subsettedGlyphs",
            "summary": "",
            "url": "classes/TTFParser.html#property_subsettedGlyphs"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024chars",
            "name": "chars",
            "summary": "",
            "url": "classes/TTFParser.html#property_chars"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024glyphs",
            "name": "glyphs",
            "summary": "",
            "url": "classes/TTFParser.html#property_glyphs"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024unitsPerEm",
            "name": "unitsPerEm",
            "summary": "",
            "url": "classes/TTFParser.html#property_unitsPerEm"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024xMin",
            "name": "xMin",
            "summary": "",
            "url": "classes/TTFParser.html#property_xMin"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024yMin",
            "name": "yMin",
            "summary": "",
            "url": "classes/TTFParser.html#property_yMin"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024xMax",
            "name": "xMax",
            "summary": "",
            "url": "classes/TTFParser.html#property_xMax"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024yMax",
            "name": "yMax",
            "summary": "",
            "url": "classes/TTFParser.html#property_yMax"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024postScriptName",
            "name": "postScriptName",
            "summary": "",
            "url": "classes/TTFParser.html#property_postScriptName"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024embeddable",
            "name": "embeddable",
            "summary": "",
            "url": "classes/TTFParser.html#property_embeddable"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024bold",
            "name": "bold",
            "summary": "",
            "url": "classes/TTFParser.html#property_bold"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024typoAscender",
            "name": "typoAscender",
            "summary": "",
            "url": "classes/TTFParser.html#property_typoAscender"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024typoDescender",
            "name": "typoDescender",
            "summary": "",
            "url": "classes/TTFParser.html#property_typoDescender"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024capHeight",
            "name": "capHeight",
            "summary": "",
            "url": "classes/TTFParser.html#property_capHeight"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024italicAngle",
            "name": "italicAngle",
            "summary": "",
            "url": "classes/TTFParser.html#property_italicAngle"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024underlinePosition",
            "name": "underlinePosition",
            "summary": "",
            "url": "classes/TTFParser.html#property_underlinePosition"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024underlineThickness",
            "name": "underlineThickness",
            "summary": "",
            "url": "classes/TTFParser.html#property_underlineThickness"
        },                {
            "fqsen": "\\TTFParser\u003A\u003A\u0024isFixedPitch",
            "name": "isFixedPitch",
            "summary": "",
            "url": "classes/TTFParser.html#property_isFixedPitch"
        },                {
            "fqsen": "\\PDF",
            "name": "PDF",
            "summary": "",
            "url": "classes/PDF.html"
        },                {
            "fqsen": "\\PDF\u003A\u003AHeader\u0028\u0029",
            "name": "Header",
            "summary": "",
            "url": "classes/PDF.html#method_Header"
        },                {
            "fqsen": "\\PDF\u003A\u003AFooter\u0028\u0029",
            "name": "Footer",
            "summary": "",
            "url": "classes/PDF.html#method_Footer"
        },                {
            "fqsen": "\\PDF\u003A\u003AChapterTitle\u0028\u0029",
            "name": "ChapterTitle",
            "summary": "",
            "url": "classes/PDF.html#method_ChapterTitle"
        },                {
            "fqsen": "\\PDF\u003A\u003AChapterBody\u0028\u0029",
            "name": "ChapterBody",
            "summary": "",
            "url": "classes/PDF.html#method_ChapterBody"
        },                {
            "fqsen": "\\PDF\u003A\u003APrintChapter\u0028\u0029",
            "name": "PrintChapter",
            "summary": "",
            "url": "classes/PDF.html#method_PrintChapter"
        },                {
            "fqsen": "\\PDF\u003A\u003ASetCol\u0028\u0029",
            "name": "SetCol",
            "summary": "",
            "url": "classes/PDF.html#method_SetCol"
        },                {
            "fqsen": "\\PDF\u003A\u003AAcceptPageBreak\u0028\u0029",
            "name": "AcceptPageBreak",
            "summary": "",
            "url": "classes/PDF.html#method_AcceptPageBreak"
        },                {
            "fqsen": "\\PDF\u003A\u003A\u0024col",
            "name": "col",
            "summary": "",
            "url": "classes/PDF.html#property_col"
        },                {
            "fqsen": "\\PDF\u003A\u003A\u0024y0",
            "name": "y0",
            "summary": "",
            "url": "classes/PDF.html#property_y0"
        },                {
            "fqsen": "\\PDF\u003A\u003ALoadData\u0028\u0029",
            "name": "LoadData",
            "summary": "",
            "url": "classes/PDF.html#method_LoadData"
        },                {
            "fqsen": "\\PDF\u003A\u003ABasicTable\u0028\u0029",
            "name": "BasicTable",
            "summary": "",
            "url": "classes/PDF.html#method_BasicTable"
        },                {
            "fqsen": "\\PDF\u003A\u003AImprovedTable\u0028\u0029",
            "name": "ImprovedTable",
            "summary": "",
            "url": "classes/PDF.html#method_ImprovedTable"
        },                {
            "fqsen": "\\PDF\u003A\u003AFancyTable\u0028\u0029",
            "name": "FancyTable",
            "summary": "",
            "url": "classes/PDF.html#method_FancyTable"
        },                {
            "fqsen": "\\PDF\u003A\u003AWriteHTML\u0028\u0029",
            "name": "WriteHTML",
            "summary": "",
            "url": "classes/PDF.html#method_WriteHTML"
        },                {
            "fqsen": "\\PDF\u003A\u003AOpenTag\u0028\u0029",
            "name": "OpenTag",
            "summary": "",
            "url": "classes/PDF.html#method_OpenTag"
        },                {
            "fqsen": "\\PDF\u003A\u003ACloseTag\u0028\u0029",
            "name": "CloseTag",
            "summary": "",
            "url": "classes/PDF.html#method_CloseTag"
        },                {
            "fqsen": "\\PDF\u003A\u003ASetStyle\u0028\u0029",
            "name": "SetStyle",
            "summary": "",
            "url": "classes/PDF.html#method_SetStyle"
        },                {
            "fqsen": "\\PDF\u003A\u003APutLink\u0028\u0029",
            "name": "PutLink",
            "summary": "",
            "url": "classes/PDF.html#method_PutLink"
        },                {
            "fqsen": "\\PDF\u003A\u003A\u0024B",
            "name": "B",
            "summary": "",
            "url": "classes/PDF.html#property_B"
        },                {
            "fqsen": "\\PDF\u003A\u003A\u0024I",
            "name": "I",
            "summary": "",
            "url": "classes/PDF.html#property_I"
        },                {
            "fqsen": "\\PDF\u003A\u003A\u0024U",
            "name": "U",
            "summary": "",
            "url": "classes/PDF.html#property_U"
        },                {
            "fqsen": "\\PDF\u003A\u003A\u0024HREF",
            "name": "HREF",
            "summary": "",
            "url": "classes/PDF.html#property_HREF"
        },                {
            "fqsen": "\\escape_data\u0028\u0029",
            "name": "escape_data",
            "summary": "",
            "url": "namespaces/default.html#function_escape_data"
        },                {
            "fqsen": "\\get_access\u0028\u0029",
            "name": "get_access",
            "summary": "",
            "url": "namespaces/default.html#function_get_access"
        },                {
            "fqsen": "\\get_list\u0028\u0029",
            "name": "get_list",
            "summary": "",
            "url": "namespaces/default.html#function_get_list"
        },                {
            "fqsen": "\\get_one\u0028\u0029",
            "name": "get_one",
            "summary": "",
            "url": "namespaces/default.html#function_get_one"
        },                {
            "fqsen": "\\query\u0028\u0029",
            "name": "query",
            "summary": "",
            "url": "namespaces/default.html#function_query"
        },                {
            "fqsen": "\\insert_get_id\u0028\u0029",
            "name": "insert_get_id",
            "summary": "",
            "url": "namespaces/default.html#function_insert_get_id"
        },                {
            "fqsen": "\\message_error\u0028\u0029",
            "name": "message_error",
            "summary": "",
            "url": "namespaces/default.html#function_message_error"
        },                {
            "fqsen": "\\message_success\u0028\u0029",
            "name": "message_success",
            "summary": "",
            "url": "namespaces/default.html#function_message_success"
        },                {
            "fqsen": "\\remove_error\u0028\u0029",
            "name": "remove_error",
            "summary": "",
            "url": "namespaces/default.html#function_remove_error"
        },                {
            "fqsen": "\\activate\u0028\u0029",
            "name": "activate",
            "summary": "",
            "url": "namespaces/default.html#function_activate"
        },                {
            "fqsen": "\\activate2\u0028\u0029",
            "name": "activate2",
            "summary": "",
            "url": "namespaces/default.html#function_activate2"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
